# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
twitter_username: fortnebula
github_username:  donnydavis

# Build settings
markdown: kramdown
#theme: patternfly
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
alert-message: ' and <a href="http://getbootstrap.com" class="alert-link">http://getbootstrap.com</a>.'
category-list: [Widgets, Charts, Layouts, Navigation]
company: Fort Nebula
navbar-pf-navbar-brand-icon: true
navbar-pf-alt-navbar-brand-icon: true
navbar-logo-icon: '/assets/dist/img/logo.svg'
navbar-logo-alt-icon: '/assets/dist/img/logo-alt.svg'
navbar-brand-icon: '/assets/dist/img/brand.svg'
navbar-brand-alt-icon: '/assets/dist/img/fn-brand.svg'
title: FortNebula
title-product: 'PatternFly Enterprise Application'
email: donny@fortnebula.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fortnebula.com" # the base hostname & protocol for your site, e.g. http://example.com
url-css-additions: '/assets/dist/css/patternfly-additions.min.css'
url-css-main: '/assets/dist/css/patternfly.min.css'
url-img: 'img/'
url-js: '/assets/dist/js/patternfly.min.js'
url-js-extra: ['//cdnjs.cloudflare.com/ajax/libs/jquery.matchHeight/0.7.0/jquery.matchHeight-min.js', '//cdnjs.cloudflare.com/ajax/libs/c3/0.4.11/c3.min.js', '//cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min.js']
nav-tertiary: false
